#!/bin/bash
# PRISM Hypertuner v2 - Automated Parameter Search for DSJC500.5 -> 48 colors
# Mission: Achieve exactly 48 colors with 0 conflicts through intelligent search

set -e

# Configuration
GRAPH="data/DIMACS_subset/DSJC500.5.col"
TARGET_COLORS=48
MAX_ATTEMPTS=100
CAMPAIGN_DIR="campaigns/hypertuning_$(date +%Y%m%d_%H%M%S)"
PRISM_CMD="cargo run --release --features cuda --"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Create campaign directory
mkdir -p $CAMPAIGN_DIR
echo -e "${BLUE}Starting hypertuning campaign for DSJC500.5 -> 48 colors${NC}"
echo "Campaign directory: $CAMPAIGN_DIR"

# Function to extract results from telemetry
extract_results() {
    local telemetry_file=$1
    if [ -f "$telemetry_file" ]; then
        jq -s 'last | {
            colors: .final_state.colors,
            conflicts: .final_state.conflicts,
            iterations: .iteration,
            runtime: .elapsed_time
        }' "$telemetry_file" 2>/dev/null || echo '{"colors": 999, "conflicts": 999}'
    else
        echo '{"colors": 999, "conflicts": 999}'
    fi
}

# Function to calculate score (lower is better)
calculate_score() {
    local colors=$1
    local conflicts=$2
    local color_diff=$((colors - TARGET_COLORS))
    if [ $color_diff -lt 0 ]; then
        color_diff=$((-color_diff))
    fi
    echo $((color_diff + conflicts * 1000))
}

# Function to generate config based on parameters
generate_config() {
    local mu=$1
    local temp=$2
    local anneal=$3
    local coupling=$4
    local output_file=$5

    cat > "$output_file" << EOF
# Auto-generated by hypertuner_v2
# Target: DSJC500.5 -> 48 colors
# Chemical Potential: $mu (requires kernel rebuild if changed)
# Generated: $(date -Iseconds)

[global]
max_attempts = 10
enable_fluxnet_rl = true
rl_learning_rate = 0.03

[phase2_thermodynamic]
initial_temperature = $temp
final_temperature = 0.001
cooling_rate = $anneal
steps_per_temp = 10000
num_replicas = 8
conflict_penalty = 20.0
color_penalty = 0.8

[phase3_quantum]
coupling_strength = $coupling
evolution_iterations = 500
transverse_field = 2.0
max_colors = 48  # NEVER exceed target!

[memetic]
population_size = 400
mutation_rate = 0.12
crossover_rate = 0.80
max_generations = 3000
local_search_depth = 50000
kempe_chain_attempts = 30
elite_percentage = 0.15
population_diversity_threshold = 0.15

[metaphysical_coupling]
feedback_strength = 1.5
geometric_weight = 0.7
topological_weight = 0.3
phase_transition_threshold = 0.8
stress_decay_rate = 0.65
entropy_coupling = 0.9
EOF
}

# Stage 1: Test baseline configurations
echo -e "\n${YELLOW}Stage 1: Testing baseline configurations...${NC}"

BEST_SCORE=999999
BEST_CONFIG=""
BEST_COLORS=999
BEST_CONFLICTS=999

# Test existing configs
for config in configs/TUNED_17.toml configs/WORLD_RECORD_ATTEMPT.toml configs/OPTIMIZED_CONFLICT_REDUCTION.toml; do
    if [ -f "$config" ]; then
        echo -e "Testing $config..."
        telemetry_file="$CAMPAIGN_DIR/baseline_$(basename $config .toml).jsonl"

        timeout 120 $PRISM_CMD \
            --graph $GRAPH \
            --config $config \
            --telemetry "$telemetry_file" \
            2>&1 | tee "$CAMPAIGN_DIR/baseline_$(basename $config .toml).log" | \
            grep -E "(Final coloring|conflicts|Phase)" || true

        result=$(extract_results "$telemetry_file")
        colors=$(echo $result | jq -r '.colors')
        conflicts=$(echo $result | jq -r '.conflicts')
        score=$(calculate_score $colors $conflicts)

        echo -e "Result: ${colors} colors, ${conflicts} conflicts (score: $score)"

        if [ $score -lt $BEST_SCORE ]; then
            BEST_SCORE=$score
            BEST_CONFIG=$config
            BEST_COLORS=$colors
            BEST_CONFLICTS=$conflicts
            echo -e "${GREEN}New best baseline!${NC}"
        fi

        # Check for immediate victory
        if [ "$colors" -eq "$TARGET_COLORS" ] && [ "$conflicts" -eq 0 ]; then
            echo -e "${GREEN}🎯 VICTORY! Achieved 48 colors with 0 conflicts!${NC}"
            cp "$config" "configs/VICTORY_DSJC500.5_$(date +%Y%m%d).toml"
            exit 0
        fi
    fi
done

echo -e "\nBest baseline: $BEST_COLORS colors, $BEST_CONFLICTS conflicts (score: $BEST_SCORE)"

# Stage 2: Targeted parameter search based on baseline
echo -e "\n${YELLOW}Stage 2: Targeted parameter search...${NC}"

# Determine search strategy based on baseline
if [ $BEST_COLORS -lt 48 ]; then
    echo -e "${BLUE}Current colors ($BEST_COLORS) < target (48) - reducing compression${NC}"
    # Need less aggressive compression
    MU_VALUES=(0.65 0.70 0.72 0.75)
    TEMP_VALUES=(2.0 2.5 3.0)
    ANNEAL_VALUES=(0.94 0.95 0.96)
    COUPLING_VALUES=(8.0 9.0 10.0)
elif [ $BEST_COLORS -gt 48 ]; then
    echo -e "${BLUE}Current colors ($BEST_COLORS) > target (48) - increasing compression${NC}"
    # Need more aggressive compression
    MU_VALUES=(0.78 0.80 0.82 0.85)
    TEMP_VALUES=(3.0 3.5 4.0)
    ANNEAL_VALUES=(0.92 0.93 0.94)
    COUPLING_VALUES=(10.0 11.0 12.0)
else
    echo -e "${BLUE}Already at target colors (48) - fine tuning for stability${NC}"
    # Fine tuning
    MU_VALUES=(0.74 0.75 0.76)
    TEMP_VALUES=(2.5 3.0 3.5)
    ANNEAL_VALUES=(0.93 0.94 0.95)
    COUPLING_VALUES=(9.5 10.0 10.5)
fi

# If we have conflicts, adjust strategy
if [ $BEST_CONFLICTS -gt 0 ]; then
    echo -e "${YELLOW}Have conflicts - prioritizing conflict resolution${NC}"
    ANNEAL_VALUES=(0.96 0.97 0.98)  # Slower cooling for conflict resolution
fi

# Parameter sweep with early termination on success
ATTEMPT=0
for mu in "${MU_VALUES[@]}"; do
    # Check if we need to update GPU kernel
    current_mu=$(grep "const float CHEMICAL_POTENTIAL" prism-gpu/src/kernels/thermodynamic.cu 2>/dev/null | grep -oE "[0-9]+\.[0-9]+" || echo "0.75")
    if [ "$current_mu" != "$mu" ]; then
        echo -e "${YELLOW}Updating chemical potential from $current_mu to $mu (requires rebuild)${NC}"
        sed -i "s/const float CHEMICAL_POTENTIAL = [0-9.]*;/const float CHEMICAL_POTENTIAL = ${mu};/" \
            prism-gpu/src/kernels/thermodynamic.cu

        echo "Rebuilding GPU kernels..."
        (cd prism-gpu && cargo build --release --features cuda)
    fi

    for temp in "${TEMP_VALUES[@]}"; do
        for anneal in "${ANNEAL_VALUES[@]}"; do
            for coupling in "${COUPLING_VALUES[@]}"; do
                ATTEMPT=$((ATTEMPT + 1))
                if [ $ATTEMPT -gt $MAX_ATTEMPTS ]; then
                    echo -e "${RED}Reached maximum attempts ($MAX_ATTEMPTS)${NC}"
                    break 4
                fi

                config_file="$CAMPAIGN_DIR/config_mu${mu}_t${temp}_a${anneal}_c${coupling}.toml"
                telemetry_file="$CAMPAIGN_DIR/sweep_mu${mu}_t${temp}_a${anneal}_c${coupling}.jsonl"

                echo -e "\n${BLUE}Attempt $ATTEMPT: μ=$mu, T=$temp, anneal=$anneal, coupling=$coupling${NC}"

                # Generate config
                generate_config $mu $temp $anneal $coupling "$config_file"

                # Run PRISM
                timeout 120 $PRISM_CMD \
                    --graph $GRAPH \
                    --config "$config_file" \
                    --telemetry "$telemetry_file" \
                    2>&1 | tee "$CAMPAIGN_DIR/attempt_${ATTEMPT}.log" | \
                    grep -E "(Final coloring|conflicts|Phase)" || true

                # Extract results
                result=$(extract_results "$telemetry_file")
                colors=$(echo $result | jq -r '.colors')
                conflicts=$(echo $result | jq -r '.conflicts')
                score=$(calculate_score $colors $conflicts)

                echo -e "Result: ${colors} colors, ${conflicts} conflicts (score: $score)"

                # Track best
                if [ $score -lt $BEST_SCORE ]; then
                    BEST_SCORE=$score
                    BEST_CONFIG=$config_file
                    BEST_COLORS=$colors
                    BEST_CONFLICTS=$conflicts
                    echo -e "${GREEN}New best: score $BEST_SCORE${NC}"
                fi

                # Check for victory
                if [ "$colors" -eq "$TARGET_COLORS" ] && [ "$conflicts" -eq 0 ]; then
                    echo -e "${GREEN}🎯 VICTORY! Achieved 48 colors with 0 conflicts!${NC}"
                    echo -e "${GREEN}Configuration: μ=$mu, T=$temp, anneal=$anneal, coupling=$coupling${NC}"

                    # Save victory config
                    victory_file="configs/VICTORY_DSJC500.5_$(date +%Y%m%d_%H%M%S).toml"
                    cp "$config_file" "$victory_file"

                    # Document the victory
                    cat > "$CAMPAIGN_DIR/VICTORY_REPORT.txt" << EOF
🎯 TARGET ACHIEVED: DSJC500.5
✅ Colors: 48 (exact chromatic number)
✅ Conflicts: 0
✅ Attempt: $ATTEMPT

Key Parameters:
- Chemical Potential μ: $mu
- Initial Temperature: $temp
- Cooling Rate: $anneal
- Coupling Strength: $coupling

Configuration saved: $victory_file
Telemetry: $telemetry_file

Timestamp: $(date -Iseconds)
EOF

                    cat "$CAMPAIGN_DIR/VICTORY_REPORT.txt"

                    # Run validation
                    echo -e "\n${YELLOW}Running validation (3 runs)...${NC}"
                    for i in 1 2 3; do
                        echo "Validation run $i..."
                        timeout 120 $PRISM_CMD \
                            --graph $GRAPH \
                            --config "$victory_file" \
                            --telemetry "$CAMPAIGN_DIR/validation_$i.jsonl" \
                            2>&1 | grep "Final coloring" || true
                    done

                    echo -e "${GREEN}✅ Victory configuration saved to: $victory_file${NC}"
                    exit 0
                fi

                # Early termination if we're very close
                if [ $score -le 2 ]; then
                    echo -e "${YELLOW}Very close to target (score $score) - entering fine-tuning mode${NC}"
                    # Adjust search to fine-tune around this point
                    MU_VALUES=($mu)
                    new_temp=$(echo "$temp - 0.2" | bc)
                    TEMP_VALUES=($new_temp $temp $(echo "$temp + 0.2" | bc))
                    new_anneal=$(echo "$anneal - 0.01" | bc)
                    ANNEAL_VALUES=($new_anneal $anneal $(echo "$anneal + 0.01" | bc))
                    new_coupling=$(echo "$coupling - 0.5" | bc)
                    COUPLING_VALUES=($new_coupling $coupling $(echo "$coupling + 0.5" | bc))
                fi
            done
        done
    done
done

# Final report
echo -e "\n${YELLOW}===== HYPERTUNING CAMPAIGN COMPLETE =====${NC}"
echo -e "Total attempts: $ATTEMPT"
echo -e "Best result: ${BEST_COLORS} colors, ${BEST_CONFLICTS} conflicts (score: $BEST_SCORE)"
echo -e "Best config: $BEST_CONFIG"

if [ $BEST_SCORE -eq 0 ]; then
    echo -e "${GREEN}✅ Target achieved but not during sweep - check baseline configs${NC}"
elif [ $BEST_SCORE -le 10 ]; then
    echo -e "${YELLOW}Very close to target! Consider fine-tuning around best config${NC}"
else
    echo -e "${RED}Target not achieved. Consider expanding parameter ranges${NC}"
fi

echo -e "\nCampaign results saved to: $CAMPAIGN_DIR"
echo -e "To analyze: jq -s '.[].final_state | {colors, conflicts}' $CAMPAIGN_DIR/*.jsonl | sort -u"